Transform prices inputs/outpus via DTO
bagrinsergiu/Sylius pull request #129
Opened 2021-09-27 10:47 UTC by brizyNicu

Changes:
- Add Output Dto and transformers for Order, OrderItem, ChannelPricing;
- Add Input Dto and transformers for ChannelPricing;
- Add a new file to register data-transformer-services and registered it in ` ApiBundle's` Extension

**Related Issues**:
- bagrinsergiu/brizy-cms-ui#2238
- bagrinsergiu/brizy-cloud-sylius-demo-template/issues/178
- bagrinsergiu/brizy-cloud-sylius-demo-template/issues/191

2021-09-28 13:48 UTC, DanxilL requested changes

2021-10-12 11:31 UTC, closed without merging

2021-10-18 08:44 UTC, brizyNicu commented on src/Sylius/Bundle/ApiBundle/DataTransformer/OrderItemReadDataTransformer.php
> +//        $output->product = $object->getProduct();
outdated

2021-10-18 08:45 UTC, brizyNicu commented on src/Sylius/Bundle/ApiBundle/Helpers/PriceTransformer.php
> +    }
outdated

2021-10-18 08:45 UTC, brizyNicu commented on src/Sylius/Bundle/ApiBundle/DataTransformer/ChannelPricingInputDataTransformer.php
> +        if ($data instanceof ChannelPricing) {
removed

2021-10-18 08:45 UTC, brizyNicu commented on src/Sylius/Bundle/ApiBundle/DTO/OrderItemRead.php
> +
outdated