Added endpoints for ProductAttribute and ProductAttributeValue
bagrinsergiu/Sylius pull request #70
Opened 2021-05-27 14:50 UTC by Malin-Cebo

| Q  | A |
| ------------- | ------------- |
| Related tickets | bagrinsergiu/brizy-cloud-sylius-demo-template/issues/127 |
| Tests |  N |

### Changelog

* New: Added endpoints for ProductAttribute and ProductAttributeValue with Subject(product) filter,  Create and Update Product with ProductAttributeValue

2021-06-09 13:59 UTC, lawliet5130 requested changes

2021-06-09 13:59 UTC, lawliet5130 commented on src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAttributeValue.xml
> +                    <attribute>sylius.api.product_attribute_value_locale_code_filter</attribute>
Locale filter needs to be upgraded.

2021-06-10 10:25 UTC, Malin-Cebo commented on src/Sylius/Bundle/ApiBundle/Doctrine/Filters/TaxRateZoneFilter.php
> +                ->setParameter('code', strripos($value, '/') ? substr(strrchr($value, "/"), 1) : $value)
Fixed

2021-06-10 10:26 UTC, Malin-Cebo commented on src/Sylius/Bundle/ApiBundle/Doctrine/Filters/TaxRateZoneFilter.php
> +                ->where('zoneId.code LIKE CONCAT(\'%\', :code, \'%\')')
Done. 
where('zoneId.code LIKE :code')

2021-06-10 10:27 UTC, Malin-Cebo commented on src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAttributeValue.xml
> +                    <attribute>sylius.api.product_attribute_value_locale_code_filter</attribute>
Done. Added new filter.

2021-06-10 15:27 UTC, lawliet5130 requested changes

2021-06-10 15:27 UTC, lawliet5130 commented on src/Sylius/Bundle/ApiBundle/Doctrine/Filters/TaxRateZoneFilter.php
> +                ->setParameter('code', $value[end($value)])
```suggestion
                ->setParameter('code', end($value))
```

2021-06-10 15:41 UTC, lawliet5130 requested changes

2021-06-10 15:41 UTC, lawliet5130 commented on src/Sylius/Bundle/ApiBundle/Doctrine/Filters/TaxRateZoneFilter.php
> +            $value = explode('/',$value);
```suggestion
            $value = explode('/', $value);
```

2021-06-10 15:44 UTC, lawliet5130 approved these changes

2021-06-10 15:47 UTC, merged